# Generated by Django 3.0.8 on 2020-07-30 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myprojects', to=settings.AUTH_USER_MODEL),
        ),
    ]
