# Generated by Django 3.0.8 on 2020-07-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_auto_20200730_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-status', '-date']},
        ),
        migrations.RemoveField(
            model_name='bug',
            name='priority',
        ),
        migrations.AddField(
            model_name='bug',
            name='tag',
            field=models.IntegerField(default=7),
        ),
    ]
