# Generated by Django 3.0.8 on 2020-08-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20200731_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='head',
            field=models.CharField(max_length=40),
        ),
    ]
