# Generated by Django 3.0.8 on 2020-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0008_auto_20200812_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagehash', models.CharField(max_length=100)),
                ('url', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
