# Generated by Django 3.0.8 on 2020-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0009_ckimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(default='pic/default_profile_photo.jpeg', upload_to='pic/'),
        ),
    ]
